### ISSUE TITLE
[Feature Reques] Anti-windup

### ISSUE THREAD

**Issue by saullipton** [mike-matera/FastPID#10]
You enabled setting the max and min output - can you also clamp the integer term to a settable limit, not just the limit of the int32? This will enable better motor tuning.

Thanks!
Saul

**Comment by mike-matera** [comment]
Hi! I'll take a look at this during my winter school break. Thanks for the request!

**Comment by ArduinoCoder** [comment]
Dear saullipton, dear mike-matera,

I faced the same issues with the FastPID code since I only wanted to serve a 12 bit output and set the limits accordingly. But I was wondering when the output passes the boundaries it took so much time until it came back from somewhere.
So I digged a bit deeper into the PID codes and also some other references. I found this blog which was very helpful for me:

http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/

There the topic of "I" part windup was addressed and I tried to implement it into FastPID's code.
It was rather simple. I only had to modify the FastPID.cpp with the following passage:

    // Limit sum to output limits so that it saturates.
    if (_sum > _outmax)
      _sum = _outmax;
    else if (_sum < _outmin)
      _sum = _outmin;

Instead of:

    // Limit sum to 32-bit signed value so that it saturates, never overflows.
    if (_sum > INTEG_MAX)
      _sum = INTEG_MAX;
    else if (_sum < INTEG_MIN)
      _sum = INTEG_MIN;

With that modification the windup is prevented and the output returns into the regulation range very fast when the feedback changes.

Attachment (modified cpp file):
[FastPID.cpp.zip](https://github.com/mike-matera/FastPID/files/2722103/FastPID.cpp.zip)

Best Regards
AC

**Comment by mike-matera** [comment]
Hi! 

@saullipton You can update the `#define` if you need to. However, I've added an example that shows how to fix overshoot without playing games with windup. The example disables the PID when you are outside of the range of regulation. You could also apply different coefficients in different ranges or regimes. This is known as "gain scheduling." Check out the "Integral Windup" section of the README. 

@ArduinoCoder the problem with tricks like this is that they make the PID mathematically incorrect. I have a different philosophy than Brett. My PID controller seeks to be simple, correct and validated. Therefore I do not add features that are better handled *outside* of the controller. Please look at the updated README for how to handle integral windup.
