### ISSUE TITLE
fixed point

### ISSUE THREAD

**Issue by koendv** [mike-matera/FastPID#18]
I'd like your thoughts on avoiding the use of floats altogether.
Patched FastPID so the library uses fixed-point integers instead of float.
You define a scale factor SCALE in FastPID.h.
Kp, Ki, Kd and hz are then fixed-point integers, witch scaling factor SCALE.
Use case is a small arm processor without FPU.
What is your opinion?

[FastPID_patch.txt](https://github.com/mike-matera/FastPID/files/9614750/FastPID_patch.txt)

**Comment by mike-matera** [comment]
Thanks for the thoughs. I don't like this change because the parameters no longer make sense based on the mathematical model of a PID controller. That's an important feature to me. This library is designed for a ATMega processor with no FPU. The `step()` function uses only integer math. Only configuring the PID requires floating point emulation, which is slow, but you only have to do once.
